### ISSUE TITLE
Could I get an example

### ISSUE THREAD

**Issue by adamgroom** [whefter/puppet-phpvirtualbox#1]
Hi

Thanks for creating this module, is it possible to get an example of how to use it?

Kind Regards
Adam

**Comment by wigglyampsltd** [comment]
I second this :)

**Comment by whefter** [comment]
Hi,

thanks for your interest. I don't actively maintain this module because I rarely use it these days (or rather, it is in use but running smoothly, so I never have to tinker with it).

I've added a basic example in a README.md. Unfortunately, I don't have the time nor the inclination to create a complete documentation, especially since all the options are rather self-explanatory.

Let me know if you need some more help.

Kind regards,
whefter
